package com.jacob.www.a2dolist;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.jacob.www.a2dolist.FriendVerify;
import com.jacob.www.a2dolist.Task;
import com.jacob.www.a2dolist.Date;

import com.jacob.www.a2dolist.FriendVerifyDao;
import com.jacob.www.a2dolist.TaskDao;
import com.jacob.www.a2dolist.DateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendVerifyDaoConfig;
    private final DaoConfig taskDaoConfig;
    private final DaoConfig dateDaoConfig;

    private final FriendVerifyDao friendVerifyDao;
    private final TaskDao taskDao;
    private final DateDao dateDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendVerifyDaoConfig = daoConfigMap.get(FriendVerifyDao.class).clone();
        friendVerifyDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        dateDaoConfig = daoConfigMap.get(DateDao.class).clone();
        dateDaoConfig.initIdentityScope(type);

        friendVerifyDao = new FriendVerifyDao(friendVerifyDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);
        dateDao = new DateDao(dateDaoConfig, this);

        registerDao(FriendVerify.class, friendVerifyDao);
        registerDao(Task.class, taskDao);
        registerDao(Date.class, dateDao);
    }
    
    public void clear() {
        friendVerifyDaoConfig.getIdentityScope().clear();
        taskDaoConfig.getIdentityScope().clear();
        dateDaoConfig.getIdentityScope().clear();
    }

    public FriendVerifyDao getFriendVerifyDao() {
        return friendVerifyDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

    public DateDao getDateDao() {
        return dateDao;
    }

}
